"""
Constants and configuration for the Telegram Rewards Bot
"""

# Conversation states
CREATING_GROUP = 0
JOINING_GROUP = 1
ADDING_HABIT = 2
ADDING_HABIT_TYPE = 3
EDITING_HABIT = 4
EDITING_HABIT_TYPE = 5
ADDING_REWARD = 6
ADDING_REWARD_TYPE = 7
CONVERTING_POINTS_FROM = 8
CONVERTING_POINTS_TO = 9
CONVERTING_POINTS_AMOUNT = 10
BUYING_ANY_REWARD = 11
ADDING_TOWNMALL_ITEM = 12
ADDING_TOWNMALL_PHOTO = 13
EDITING_TOWNMALL_ITEM = 14
EDITING_TOWNMALL_PHOTO = 15
EDITING_REWARD_NAME = 16
EDITING_REWARD_PRICE = 17
